# -*- coding: utf-8 -*-
"""CBz2_Operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRw7crdLitUf7qWRStM839Ze6hyaMN8f
"""

#add,sub,div,mul
#find 56 to the power 5
#write 4 crore using **
#write the avogadro's number using 'e' notation

a=100
b=200
c=a+b
print(c)

c=a-b
print(c)

c=a*b
print(c)

c=a/b
print(c)

56**5

4*10**7

6.022e23

6.022e5

10*10**4

50*10**5

# prompt: create some examples of assignment operators in python

x = 5
x += 3  # x is now 8 (equivalent to x = x + 3)
print(f'x after += 3: {x}')

y = 10
y -= 4  # y is now 6 (equivalent to y = y - 4)
print(f'y after -= 4: {y}')

z = 7
z *= 2  # z is now 14 (equivalent to z = z * 2)
print(f'z after *= 2: {z}')

w = 20
w /= 5  # w is now 4.0 (equivalent to w = w / 5)
print(f'w after /= 5: {w}')

a = 15
a %= 4  # a is now 3 (equivalent to a = a % 4)
print(f'a after %= 4: {a}')

b = 2
b **= 3  # b is now 8 (equivalent to b = b ** 3)
print(f'b after **= 3: {b}')

c = 10
c //= 3  # c is now 3 (equivalent to c = c // 3)
print(f'c after //= 3: {c}')

d = 12
d &= 3  # d is now 0 (equivalent to d = d & 3)
print(f'd after &= 3: {d}')

e = 5
e |= 3  # e is now 7 (equivalent to e = e | 3)
print(f'e after |= 3: {e}')

f = 5
f ^= 3  # f is now 6 (equivalent to f = f ^ 3)
print(f'f after ^= 3: {f}')

g = 16
g >>= 2  # g is now 4 (equivalent to g = g >> 2)
print(f'g after >>= 2: {g}')

h = 4
h <<= 3  # h is now 32 (equivalent to h = h << 3)
print(f'h after <<= 3: {h}')

a=10
a+=5
print(a)

b=20
b-=12
print(b)

