# -*- coding: utf-8 -*-
"""CBz3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIuTfFdgmOmFS6VdqITnq4xqcCDGEt8G
"""

print(" My name is Arya and my age is 21" )

a=10
b=20
c=30
d=a+b+c
print(d)

100/5

a=str("123")
b=int(123)
print(b)
c=b+7
print(c)

num=3.14
num2=int(num)
print(num2)

a="10"
b="20"
c=int(a)
d=int(b)
print(c,d)
e=c+d
print(e)

width=12
height=8
area=width*height
print(area)

25%4

a=10.24
b=25
c=a+b
print(c,type(c))

(10+3) * 2-5/2

first="Arya"
last="Bhor"
print(first+" "+last)

string1="python"
string1*3

integer=100
string2="python"
string3=str(integer)
print(string2+string3)

text="Hello World"
print(text[0:1])

text2="Computer"
print(text2[-1:])

string4="programming"
print(string4[3:7])

text="Hello , Python"
print(text[:5])

string="apple"
print(string.upper())

string2="banana"
print(string2.count('a'))

string1="Good morning"
print(string1.replace('morning','evening'))

word="Today is good day"
print(word.find('day'))

name=input("Enter your name ")
print(name)
print(name[::-1])

String="Reading Books"
print(len(String))

String5="Hello World"
print(String5.startswith("Hello"))

num=int(input("Enter a number "))
if num%2==0:
    print("Even")
else:
    print("Odd")

string="python program"
print(string.title())

string="Elephant"
print(string)

birth=int(input("Enter your birth year "))
age=2025-birth
print("Your age is ",age)

i=1
while i<10:
    print(i *"*")
    i=i+1

#swapping of integer values
a=10
b=20
a,b=b,a
print(f' a is {a} and b is {b}')

