# -*- coding: utf-8 -*-
"""CBz4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VzxMWY6Tl9zzVHhTRTnVTor4S3exzc96
"""

#if else statements

if 3 > 4 :
  print("3 is greater than 4")
else :
  print("3 is not greater than 4")

a=int(input("Enter a number:"))
if a%2==0:
  print("The number is even")
else:
  print("The number is odd")

num1=int(input("Enter a nmuber"))
oper=input("Enter the operation + - * / ")
num2=int(input("Enter a number"))
if oper=="+":
  print(num1+num2)
elif oper=="-":
  print(num1-num2)
elif oper=="*":
  print(num1*num2)
elif oper=="/":
  print(num1/num2)
else:
  print("Invalid operation")

age=int(input("Enter your age : "))
if 0<= age<=12:
  print("You are a child")
elif 13<= age<=19:
  print("You are a teenager")
elif 20<= age<=59:
  print("You are an adult")
elif age>=65 :
  print("You are a senior citizen")
else :
  print("Invalid age")

income=int(input("enter your income"))
if 0<= income <=15000:
  print("You will get 5% discount")
elif 15001 <= income <=20000:
  print("You will get 10% discount")
elif 20001 <= income <=50000:
  print("You will get 20% discount")
elif 50001 <= income <=80000:
  print("You will get 30% discount")
elif income >=80001:
  print("You will get 40% discount")
else:
  print("Invalid income")

