# -*- coding: utf-8 -*-
"""Cbz6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Jnsn3OmuTpUQqKarY3mQOCtlpbLKFXy
"""

income=int(input("Enter your income : "))
bill=float(input("Enter your bill :"))
if 0<= income <15000:
  print("Your discount is 10%")
  discounted_amount=bill*10/100
  print("your discount is:",discounted_amount)
  final=bill-discounted_amount
  print("you have to pay :",final)
elif 15000<= income <20000:
  print("Your discount is 20%")
  discounted_amount=bill*20/100
  print("your discount is:",discounted_amount)
  final=bill-discounted_amount
  print("you have to pay :",final)
elif 20000<= income <50000:
  print("Your discount is 30%")
  discounted_amount=bill*30/100
  print("your discount is:",discounted_amount)
  final=bill-discounted_amount
  print("you have to pay :",final)
elif 50000<= income <80000:
  print("Your discount is 40%")
  discounted_amount=bill*20/100
  print("your discount is:",discounted_amount)
  final=bill-discounted_amount
  print("you have to pay :",final)
elif income >=80000 :
  print("Your discount is 50%")
  discounted_amount=bill*50/100
  print("your discount is:",discounted_amount)
  final=bill-discounted_amount
  print("you have to pay :",final)
else :
  print("Invalid input")

li=[[1,2,3],[5,8,9]]
print(li)

# prompt: how to change elements in list inside list

li[0][1] = 10
li

li[1][2]=20
li

Cb=[1, 2, 3, 3, 2, 34, 54, 'Bun Maska', '🍔🍅', True, 5.555, [6, 5, '🍗']]

Cb[8]='🍔🍟'
Cb

Cb[-1][-1]='😊'
Cb

fruits=['mango','banana','apple','watermelon']
fruits

fruits[3][:5]

fruits.append('orange')
fruits

fruits.insert(2,'grapes')
fruits

items=['watermelon',
 'Apple',
 '🍌',
 'Banana',
 'Mango',
 'orange',
 '🍅',
 '🍅',
 '🍅',
 '🍋',
 '🍋']

items

items.insert(9,"😊")
items

items.remove("Banana")

items

items.pop(2)

items

items.sort() #ascending

items

items.sort(reverse=True)  #descending sort
items

#create a simple list
#try positive and negative index
# try append,pop,remove, insert,extend,clear
#reverse the list without reverse
#if all numbers ,find the sum
# write difference between append and extend
#write the difference between pop() and remove
#update a list

a=[12,40,32,60,86,92]

a[5]

a[-2]

a.append(100)
a

a.pop(4)

a.remove(12)

a.insert(2,68)

a

a.extend("78")

a.clear()

a

b=['apple','banana','orange','watermelon','tomato']
b

b.sort(reverse=True)
b

num=[12,32,45,6,7,89,90]

num = [12, 32, 45, 6, 7, 89, 90]
total_sum = sum(num)
print(total_sum)

#append and extend
#append:the append is use to insert the element in the list .the element is inserted at the last index of list.
#extend: the extend is use to insert the element in the list , it extend the given elements and insert it at last but by seperation for e.g "Amit" --> 'A','m','i','t'.

#remove and pop
#remove : It is use to remove the element from the list , it has to define or describe the element . does not work with directly giving indexing.
#pop : the pop is use to remove or pop the element from a list by defining the index , if no index is provided it remove the last element from the list.

import pandas as pd

cars=pd.read_html("https://en.wikipedia.org/wiki/Car")

cars

type(cars)

cars=pd.DataFrame(cars[0])

cars.info

cars.head()

cars.describe

cars.tail()

cars.head(10)

print(cars.isnull())

cars.isnull().sum()

cars.duplicated

