# -*- coding: utf-8 -*-
"""Cbz8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdSduN9B7OoddRkOUBqO6l45rIEhFA97
"""

#dir is use to know which operations can be performed on a specific elements
#lets use string
dir("Arya")

#integer dir
dir(20)

# tuple --> tuple is immutable ,values cannot be changed if inserted .
# It is ordered collection. It allows duplicates. A tuple can contain different datatypes.

t=(12,42,57,87,92)
t

dir(t)

t[2]

import numpy as np
dir(np)

len(t)

241-(-241)+1

t1=(1,2,3)
t2=(1,2,3)
#if else
#tell if the len of 2 tuple is same
if len(t1)==len(t2):
    print("same")
else:
    print("not same")

