# -*- coding: utf-8 -*-
"""CBz_Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hk5NJjRIdmF_WtrMipbBkvbdHcwrqorC
"""

@z=arya
print(@z)

*a="Storage"
print(*a)

$product="Packages"
print($product)

12items=12
print(12items)

# Commented out IPython magic to ensure Python compatibility.
# %pr="82"
print(%pr)

print="APPLE"

del print

int=21

del int

float=40.24

del float

bool=True

del bool

type=int
print(type)

del type

num=20
num2=float(num)
print(num2)

a=10
b=float(a)
print(b)

n1=45
n2=float(n1)
print(n2)

f1=92.5
f2=str(f1)
print(f2)

word="CloudBlitz"
print(word[:5])

print(word[::2])

print(word[::-1])

print(word[5:])

print(word[-10:-5])

print(word[-10:-2])

a="developers"
b="python"
c="data"
d="machine learning"
e="artificial"
f="inteligence"
g="notebook"
h="programming"
i="openai"
j="statistics"
#hon #velo #ata # achine # tifics #tebo #gram #pen #stics

print(a[2:6])
print(b[3:])
print(c[1:])
print(d[1:7])
print(e[2:7])
print(f[0:5])
print(h[3:7])
print(i[1:4])
print(j[5:])

print(a[::-1])
print(b[::-1])
print(c[::-1])
print(d[::-1])
print(e[-10:-7])

a="Aprhyla_Bkhwotr"
print(a[::2])

b="LmeptpspDpolPlyatuhiokn"
print(b[::2])

c="A   r   y   a"
print(c[::2])

d="Tlhiipsn _ifsk lplywtkhlofn"
print(d[::2])

s="ClOuDbLiTz"

s

s=s.capitalize()

s

